### ISSUE TITLE
Comments behave oddly in do statement

### ISSUE THREAD

**Issue by arianvp** [chrisdone/hindent#354] opened 2016-11-25 12:30 UTC
```haskell
main :: IO ()
main = do
  -- print stuff
  putStrLn "hey"
  -- read the environment
  x <- lookupEnv "HEY"
  -- we are done
  return ()
```

is hindented to:

```haskell
main :: IO ()
main
-- print stuff
 = do
  putStrLn "hey"
  -- read the environment
  x <- lookupEnv "HEY"
  -- we are done
  return ()
```

Which is not what I would expect

**Comment by tfausak** [comment] 2016-11-28 20:12
This is a duplicate of #316.

**Comment by chrisdone** [comment] 2017-01-06 10:39
Closing as dupe.

**Closed by chrisdone** 2017-01-06 10:39 UTC
