### ISSUE TITLE
Bad interaction with qualified infix operators

### ISSUE THREAD

**Issue by grantwwu** [chrisdone/hindent#337] opened 2016-10-15 23:59 UTC
`deref = (IM.!) . blocks`

gets turned into

`deref = IM.(!) . blocks`

which is fine, but formatting that turns it into

`deref = IM . (!) . blocks`

which is not right.

**Comment by tfausak** [comment] 2016-10-17 17:42
I think this is a duplicate of #273. Also it's already been fixed on master.

```
$ cat Example.hs 
deref = (IM.!) . blocks

$ cat Example.hs | hindent
deref = (IM.!) . blocks
```

**Closed** 2016-11-24 14:07 UTC
