### ISSUE TITLE
hindent mode not working in emacs

### ISSUE THREAD

**Issue by CSRaghunandan** [chrisdone/hindent#189] opened 2016-06-03 13:30 UTC
Hello, 

I just started out using emacs and haskell-mode. I installed hindent using `cabal install hindent`  and installed hindent package using the package-install in emacs. 
But once I enter M-q, emacs prompts an error message "searching for program:no such file or directory hindent. Any idea how I can fix this ? 

Thanks

**Comment by FrancisMurillo** [comment] 2016-06-05 10:43
Oh, I had the same problem. Have you tried to call `hindent` at the command line? I used `stack` instead as it is much more convenient. 

`stack install hindent`

**Comment by CSRaghunandan** [comment] 2016-06-06 08:57
well, it says "command not found."  Ah. so what should I do now? Should I search for hindent path and add it to the list of environment variables ?
and I'm running on GHC platform 8.0.1, would that cause any problems ?

**Comment by FrancisMurillo** [comment] 2016-06-06 09:48
@CSRaghunandan: Yes, the basic idea is that you have the `hindent` command at your terminal so that Emacs can call it with something like `shell-command-on-region`, so indeed `hindent` must be in your environment path. 

I do suggest installing [http://docs.haskellstack.org/en/stable/README/](stack) as it is easy to install and easy to setup the tools for the command line. 

If that doesn't work and running `hindent` within Emacs run an error. Then my final suggestion is to use `exec-path-from-shell` to make sure Emacs is passed the environment path. 

```emacs-lisp
      (use-package exec-path-from-shell
        :ensure t
        :config
        :disabled t
        (exec-path-from-shell-initialize))
```

For the second point, I don't think the version would be a problem. Good luck

**Comment by CSRaghunandan** [comment] 2016-06-06 19:52
Thanks a lot for the replies. I'll install hindent via haskell stack and try hindent-mode again and get back.
ps. I already have exec-path-from-shell package installed 👍

**Comment by sigrlami** [comment] 2016-07-20 00:31
Got the same issue
1. installed via stack with `stack install hindent` puted to `~/.local/bin/hindent`
2. re-install `hindent-mode`, got 
`In end of data:
hindent.el:271:1:Warning: the function `jump' is not known to be defined.
``
3. Add hindent-mode hook to .emacs

And it's not working. How can I fix this?

**Comment by sigrlami** [comment] 2016-07-20 00:55
@CSRaghunandan  ok, so this error is not reproducing if you running emacs from terminal, only from graphical mode. If you start it from the shell, emacs will inherit PATH from the shell, and you should be able to run it. 

To do it in graphical mode you need to add `~/.local/bin` to PATH in your `.bash_profile` for Fedora or `.profile` for Ubuntu

**Comment by FrancisMurillo** [comment] 2016-07-20 01:34
@sigrlami I just had my pc nuked two days ago and reinstalled a fresh copy of ArchLinux.
I reinstalled `stack`, `hindent` and `structured-haskell-mode` and what have you `.emacs.d`. I can run `hindent` both in the terminal and emacs and it still works for me.

**Comment by sigrlami** [comment] 2016-07-20 01:37
@FrancisMurillo `Fedora 23/24`, `Ubuntu 14.04` having this issue. My fix works there, not much work, but it's more related to Emacs installation (I use the one provided via distribution)

**Comment by chrisdone** [comment] 2016-08-26 07:49
Looks like everyone solved their issue. Closing. 🎉

**Closed by chrisdone** 2016-08-26 07:49 UTC
Labels: component: emacs, priority: high, type: discussion

**Comment by WolfFinster** [comment] 2017-12-26 00:25
I got the same issue. I installed hindent via stack, as described on https://github.com/commercialhaskell/hindent in the install section. I then moved hindent to `/usr/local/bin` and added 

```
(add-to-list 'load-path "/usr/local/bin")
(require 'hindent)
(add-hook 'haskell-mode-hook 'hindent-mode)
```


to my init.el, but I too get "cannot open load file: No such file or directory"
