### ISSUE TITLE
GADTs indented extremely

### ISSUE THREAD

**Issue by arianvp** [chrisdone/hindent#330] opened 2016-10-10 08:52 UTC
Got:

``` haskell
data Req a where
        GetAllUserIds :: Req [Id]
        GetUserDataById :: Id -> Req UserData
        GetFriendsForUser :: Id -> Req [Id]
        GetBooksForUser :: Id -> Req [Id]
        GetAllBookIds :: Req [Id]
        GetBookDataById :: Id -> Req BookData
        GetAuthorsForBook :: Id -> Req [Id]
```

Expected:

``` haskell
data Req a where
  GetAllUserIds :: Req [Id]
  GetUserDataById :: Id -> Req UserData
  GetFriendsForUser :: Id -> Req [Id]
  GetBooksForUser :: Id -> Req [Id]
  GetAllBookIds :: Req [Id]
  GetBookDataById :: Id -> Req BookData
  GetAuthorsForBook :: Id -> Req [Id]

```

**Comment by tfausak** [comment] 2016-10-11 13:53
Is this a duplicate of #322?

**Closed** 2016-11-24 14:07 UTC
